# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33172b25c9121e997033e23c8a6002c0e1560e9fc26d7b767a317deb44c2875232ba73ac11651bfeb2263eb3d8d17f0f38fe758e63fb4b85ffbe72b60c6d8d4b

test:
  secret_key_base: f0797b3c7345fff94b148741319ce1d0331eb6a715d816a411bd87b5ccd5ff69dc538f7bb157aa2e70e2dac9bc7b362f4aed999e2b161b7df92a5134096e6739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
